Repository humanmade/altis-enhanced-search, pull requests merged in 2020-05, with the labels that each got.

#66 Provide full list of types and stati to ElasticPress
  inc/namespace.php
Labels: backport v1-branch, backport v2-branch, backport v3-branch

#65 Setting HM_ENV_TYPE throws a fatal error#
  inc/namespace.php
Labels: backport v3-branch

#70 Fix a fatal error reading Altis config
  inc/namespace.php
Labels: bug
