Repository humanmade/altis-enhanced-search, pull requests merged in 2021-04, with the labels that each got.

#185 Add autosuggest endpoint handling
  inc/namespace.php
Labels: backport v4-branch, backport v5-branch, backport v6-branch, backport v7-branch

#187 [Backport v6-branch] Add autosuggest endpoint handling
  inc/namespace.php
Labels: backport v5-branch

#190 Dont append port number for 80 or 443
  inc/namespace.php
Labels: backport v4-branch, backport v5-branch, backport v6-branch, backport v7-branch

#191 Fix ES index and sync healthchecks
  inc/namespace.php
Labels: backport v5-branch, backport v6-branch, backport v7-branch

#200 Fix `--per-page` doc parameter
  docs/reindexing-content.md
Labels: backport v7-branch

#204 Check for a package ID before checking file exists
  inc/packages/namespace.php
Labels: backport v5-branch, backport v6-branch, backport v7-branch

#209 remove extra space
  inc/namespace.php
Labels: backport v7-branch
