Repository humanmade/altis-enhanced-search, pull requests merged in 2021-07, with the labels that each got.

#246 Fix strict search mode for terms and users
  inc/namespace.php
Labels: backport v7-branch

#252 Fix phrase query for terms and users
  inc/namespace.php
Labels: backport v7-branch, backport v8-branch

#258 Prevent EP from checking the db during install
  inc/namespace.php
Labels: backport v7-branch, backport v8-branch

#261 [docs] Add a note about Elastic results availability during (re-)index
  docs/reindexing-content.md
Labels: backport v8-branch
